/**
 * Storage for all the strings in project; change once, use everywhere ;)
 *
 * @module helpers/strings
 * @license MIT
 */

module.exports = {
  reportThankYouMessage: 'Спасибо за то, что сообщили нам о нарушении! Наши модераторы немедленно рассотрят вашу заявку и предпримут все необходимое(^_<)',
  banMessage: 'На вас подали жалобу, и наши модераторы приняли решение о вашей блокировке.  Если это ошибка, то обращайтесь к администратору @dsl1500 и мы посмотрим, что можно сделать;)',
  loadingMessage: '😊 Загрузка...',
  askForUsername: 'У вас нет никнейма! Пожалуйста заполните его в настройках телеграмма.',
  deprecatedMessage: 'Пролестните страницу вниз ⤵️',
  initialMessage: 'Добро пожаловать, это Job Maker DVFU🎆! Мы рады, что вы пользуетесь нашими услугами и надеемся, что вы тоже останетесь довольны!(◕‿-)',
  mainMenuMessage: 'Выберите "Профиль" если ищите задание, либо – "Найти исполнителей".".',
  noJobsExistMessage: 'У вас нет ни одного задания. Но вы можете его создать. (^_~)',
  clientMenuMessage: 'Пожалуйста, выберите нужную опцию из меню',
  selectLanguageMessage: 'Пожалуйста, выберите язык, который вы будете использовать для написания задания, вы увидите только тех исполнителей, которые выбрали этот язык в качестве разговорного.',
  selectSupercategoryMessage: 'Пожалуйста, выберите категорию вашего задания.',
  selectCategoryMessage: 'Пожалуйста, выберите категорию вашего задания.',
  selectJobHourlyRateMessage:  'Укажате примерную цену, которую вы готовы заплатить. Конкретная цена обговаривается лично с исполнителем.',
  addJobDescriptionMessage: 'Пожалуйста, напишите ваше задание (50-500 знаков). Оно будет видно для исполнителей. Будьте кратки, детали обговариваются лично.',
  jobDescriptionErrorMessage: 'Вы уверены, что ваше описание содержит от 50-500 символов?',
  bioErrorMessage: 'Убедитесь, что ваш профиль содержит не более 150 символов.',
  addJobDescriptionHideKeyboardMessage: 'Вы можете отменить создание задания в любой момент.',
  addBioHideKeyboardMessage: 'Вы можете отменить в любой момент.',
  filledEverythingMessage: 'Круто! Ваш профиль заполнен. Сейчас вы можете ожидать задания.',
  fullFreelancerMessageAvailable: 'Ваш профиль заполнен! Сейчас вы можете ожидать задания.',
  fullFreelancerMessageBusy: 'Ваш профиль заполнен! Однако, вам не будут приходить задания, пока ваш статус "Занят(а).',
  emptyFreelancerMessage: 'Добро пожаловать в профиль! Пожалуйста, напишите информацию "О себе", выберите свой язык, примерную сумму, за которую готовы работать, а также категории заданий.',
  missingFreelancerMessage: 'Добро пожаловать в профиль! Пожалуйста, напишите информацию "О себе", выберите свой язык, примерную сумму, за которую готовы работать, а также категории заданий.',
  helpMessage: 'If you want to learn more about this bot, please go to arbeitbot.com.\n\nIf you have any questions, concerns or just found a bug, please contact us at @arbeit_bot_support.\n\nIn case you want to see the code of @arbeit_bot on GitHub, please follow the link provided below. We would appreciate if you could star our repository as well.\n\nThank you a lot for your support!',
  becameBusyMessage: 'Вы изменили ваш статус на "Занят(а)". Это значит, что вы не будете получать задания, пока не изменить свой статус на "Доступен(а)',
  becameAvailableMessage: 'Вы изменили свой статус на "Доступен(а)".Вы будете получать задания, пока не измените свой статус на "Занят(а).',
  missingBecameBusyMessage: 'Вы изменили свой статус на "Занят(а). Но это не имеет значение если  вы не заполнили профиль, так как не сможете получать задания. (/◔ ◡ ◔)/',
  missingBecameAvailableMessage: 'Вы изменили свой статус на "Доступен(а)". Но это не имеет значение если  вы не заполнили профиль, так как не сможете получать задания. (/◔ ◡ ◔)/',
  jobCreationSuccessMessage: 'Круто! Задание создано, мы отправили его вам ниже ⤵️',
  pickFreelancersMessage: 'Пожалуйста, выберите тех, кому отправить предложение о выполнении работы.',
  editBioMessage: 'Пожалуйста, введите информацию о себе (максимально 150 символов). Пишите коротко и ясно. Также можно добавить ссылку на свой профиль в социальных сетях.',
  selectCandidateMessage: 'Выберите того, кто вам нравится больше всего.',
  changedBioMessage: 'Поздравляем! Информация о вас:\n\n',
  notChangedBioMessage: 'Информация о вас не была изменена.\n\n',
  yourCurrentBio: 'О себе:',
  editHourlyRateMessage: 'Задания с какой оплатой вы хотите получать?',
  editLanguageMessage: 'На каких языках вы говорите? Вы будете получать задания, написанные только на этом языке.',
  pickCategoriesMessage: 'Что вы готовы делать. Вы будете получать задания в выбранной категории',
  suggestCategoryMessage: 'Предложить собственную категорию администратору',
  waitContractorResponseMessage: 'Вы отправили предложение выбранному исполнителю. Пожалуйста подождите пока он примет либо откажется от него, либо выберите другого исполнителя если вам надоело ждатьℹ️',
  acceptOrRejectMessage: 'Поздравляем! У вас новое предложение! Пожалуйста, примите или откажитесь.',
  freelancerInterestedNotification: ' Исполнитель заинтересовался в вашем предложении ',
  contactWithFreelancerMessage: 'Прекрасно! Исполнитель согласен на ваше предложение! Пожалуйста, свяжитесь с ним лично, и оцените его после выполненной работы.',
  contactWithClientMessage: 'Замечательно! Вы приняли предложение. Сейчас свяжитесь с заказчиком лично и оцените его, когда сделаете свою работу.',
  rateFreelancerMessage: 'Оцените исполнителя. Насколько хорошо выполнена работа?',
  rateClientMessage: 'Оцените заказчика. Было ли вам комфортно с ним работать?',
  reviewFreelancerMessage: 'reviewFreelancerMessage',
  reviewClientMessage: 'reviewClientMessage',
  thanksReviewMessage: 'Спасибо за отзыв!',
  youWereRated: 'Вас оценили ',
  clientHasChosenAnotherFreelancer: 'Заказчик выбрал другого исполнителя.',
  noCandidatesMessage: 'К сожалению, на данный момент нет доступных исполнителей 😥 Попробуйте позже или создайте новое задание.',
  thisWorkIsRemoved: 'Задание было удалено ✌️',
  thisDraftIsRemoved: 'Что-то было удалено ✌️',
  shareProfile: 'Поделиться профилем',
  mainMenuOptions: {
    findJobs: '🎅 Профиль',
    findContractors: '⛏ Задания',
    help: '☂ Помощь',
  },
  clientMenuOptions: {
    postNewJob: '🔨 Создать задание',
    myJobs: '🛠 Созданные задания',
    back: '🔙 Назад',
  },
  freelanceMenuOptions: {
    editBio: '😎 О себе',
    addBio: '😎 О себе',
    editCategories: '📌 Категории',
    addCategories: '📌 Категории',
    editHourlyRate: '💲 Оплата',
    addHourlyRate: '💲 Оплата',
    back: '🔙 Назад',
    busy: '⚒ Занят(а)',
    available: '✅ Доступен(а)',
    addLanguage: '🇷🇺 Добавить язык',
  },
  hourlyRateOptions: [
    '0₽ – 50₽', '50₽ – 250₽', '250₽ – 500₽',
    '500₽ – 1000₽', '1000₽ – 5000₽', '5000+'
    
  ],
  selectedCategory: '✅ ',
  selectedHourlyRate: '✅ ',
  selectedLanguage: '✅ ',
  categoryLeft: '<',
  categoryRight: '>',
  inlineSeparator: '~',
  categoryInline: 'cI',
  hourlyRateInline: 'hRI',
  languageInline: 'lanI',
  adminBanInline: 'abI',
  freelancerInline: 'fI',
  freelancerPageInline: 'fPI',
  jobManageInline: 'jMI',
  freelancerJobInline: 'fJI',
  selectFreelancerInline: 'sFI',
  selectAnotherFreelancerInline: 'sAFI',
  freelancerAcceptInline: 'fAI',
  askRateClientInline: 'aRCI',
  askRateFreelancerInline: 'aRFI',
  rateClientInline: 'rCI',
  rateFreelancerInline: 'rFI',
  completeJobInline: 'cJI',
  reportJobInline: 'rpJI',
  reportFreelancerInline: 'rpFI',
  reportClientInline: 'rpCI',
  cancelJobCreationInline: 'cJCI',
  cancelBioEnterInline: 'cBEI',
  inputLanguageInline: 'iLI',
  inputSupercategoryNameInline: 'iSCNI',
  inputCategoryNameInline: 'iCNI',
  inputHourlyRateInline: 'iHRI',
  inputJobDescriptionInline: 'iJDI',
  inputBioCancelInline: 'iBCI',
  jobCreationState: 'jobCreationState',
  inputBioState: 'inputBioState',
  inputLanguageState: 'inputLanguageState',
  inputCategoryNameState: 'inputCategoryNameState',
  inputHourlyRateState: 'inputHourlyRateState',
  inputJobDescriptionState: 'inputJobDescriptionState',
  inputReportMessage: 'inputReportMessage',
  cancel: '❌ Отмена',
  jobCreateCancel: '❌ Отмена',
  selectFreelancerCancel: '❌ Отмена',
  jobSendAllFreelancers: 'Отправить всем',
  jobRefresh: 'Обновить',
  jobDelete: 'Удалить',
  jobEdit: 'Изменить',
  jobSelectFreelancer: 'Выбрать исполнителя',
  jobSelectAnotherFreelancer: 'Выбрать другого исполнителя',
  jobBackPage: '<',
  jobNextPage: '>',
  interestedOption: '✅',
  notInterestedOption: '❌',
  acceptOption: '✅',
  refuseOption: '❌',
  pendingOption: '🕒',
  star: '⭐',
  bioReviews: 'Reviews:',
  saveReviewOption: 'saveReview',
  adminNotifications: {
    adminBanReviewInline: 'aBRI',
    adminDeleteReviewInline: 'aDRI',
    adminOkReviewInline: 'aORI',
    adminReviewDecision: 'Moderators have made a decision about the review.',
  },
  jobStates: {
    searchingForFreelancer: 'searchingForFreelancer',
    freelancerChosen: 'freelancerChosen',
    finished: 'finished',
    // todo: need to delete this later
    frozen: 'frozen',
    banned: 'banned',
    rated: 'rated',
    removed: 'removed',
  },
  reviewTypes: {
    byClient: 'byCl',
    byFreelancer: 'byFl',
  },
  freelancerOptions: {
    interested: 'Сделаем',
    notInterested: 'Не интересно',
    report: '❗️ Пожаловаться',
  },
  freelancerAcceptOptions: {
    accept: '✅ Принять',
    refuse: '❌ Отказаться',
  },
  jobFinishedOptions: {
    rate: '⭐ Оценить',
    report: '❗️ Пожаловаться',
  },
  report: {
    thanks: 'Спасибо!',
    reason: 'Причина  жалобы?',
  },
  rateOptions: {
    back: '🔙 Назад',
    oneStar: '⭐',
    twoStars: '⭐⭐',
    threeStars: '⭐⭐⭐',
    fourStars: '⭐⭐⭐⭐',
    fiveStars: '⭐⭐⭐⭐⭐',
  },
  rateOptionsArray: [
    '⭐', '⭐⭐', '⭐⭐⭐', '⭐⭐⭐⭐', '⭐⭐⭐⭐⭐',
  ],
  shouldUpdateJobMessage: 'shouldUpdateJobMessage',
  shouldUpdateFreelancerMessage: 'shouldUpdateFreelancerMessage',
  shouldMakeInterested: 'shouldMakeInterested',
  newReview: 'newReview',
};
